package lk.dialoglab.ezcash.domain;
// Generated Nov 3, 2015 2:14:18 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AssignedAtm generated by hbm2java
 */
@Entity
@Table(name="assigned_atm"
    ,catalog="cashatm"
)
public class AssignedAtm  implements java.io.Serializable {


     private Integer assignId;
     private Atm atm;
     private Operator operator;

    public AssignedAtm() {
    }

    public AssignedAtm(Atm atm, Operator operator) {
       this.atm = atm;
       this.operator = operator;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="assignID", unique=true, nullable=false)
    public Integer getAssignId() {
        return this.assignId;
    }
    
    public void setAssignId(Integer assignId) {
        this.assignId = assignId;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="atm_id", nullable=false)
    public Atm getAtm() {
        return this.atm;
    }
    
    public void setAtm(Atm atm) {
        this.atm = atm;
    }
@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="operator_id", nullable=false)
    public Operator getOperator() {
        return this.operator;
    }
    
    public void setOperator(Operator operator) {
        this.operator = operator;
    }




}


