package lk.dialoglab.ezcash.domain;
// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssignedAtmId generated by hbm2java
 */
@Embeddable
public class AssignedAtmId  implements java.io.Serializable {


     private int operatorId;
     private int atmId;

    public AssignedAtmId() {
    }

    public AssignedAtmId(int operatorId, int atmId) {
       this.operatorId = operatorId;
       this.atmId = atmId;
    }
   


    @Column(name="operator_id", nullable=false)
    public int getOperatorId() {
        return this.operatorId;
    }
    
    public void setOperatorId(int operatorId) {
        this.operatorId = operatorId;
    }


    @Column(name="atm_id", nullable=false)
    public int getAtmId() {
        return this.atmId;
    }
    
    public void setAtmId(int atmId) {
        this.atmId = atmId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AssignedAtmId) ) return false;
		 AssignedAtmId castOther = ( AssignedAtmId ) other; 
         
		 return (this.getOperatorId()==castOther.getOperatorId())
 && (this.getAtmId()==castOther.getAtmId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOperatorId();
         result = 37 * result + this.getAtmId();
         return result;
   }   


}


