package lk.dialoglab.ezcash.domain;

// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Atm generated by hbm2java
 */
@Entity
@Table(name = "atm", catalog = "cashatm")
public class Atm implements java.io.Serializable {

    private Integer atmId;
    private AtmLocation atmLocation;
    private String atmName;
    private Date installedDate;
    private String serialNo;
    private String status;
    private String alert;
    private Date livePktTime;
    private int tray1;
    private int tray2;
    private int reject1;
    private int reject2;
    private String atmCode;
    private Integer tray1NoteValue;
    private Integer tray2NoteValue;
    private Integer batLevel;

    private Set<CashOut> cashOuts = new HashSet<CashOut>(0);
    private Set<Alerts> alertses = new HashSet<Alerts>(0);
    private Set<AtmReload> atmReloads = new HashSet<AtmReload>(0);
    private Set<AssignedAtm> assignedAtms = new HashSet<AssignedAtm>(0);
    private Set<Notes> noteses = new HashSet<Notes>(0);

    public Atm() {
    }

    public Atm(Date livePktTime, int tray1, int tray2, int reject1, int reject2, String atmCode) {
        this.livePktTime = livePktTime;
        this.tray1 = tray1;
        this.tray2 = tray2;
        this.reject1 = reject1;
        this.reject2 = reject2;
        this.atmCode = atmCode;
      // this.batLevel= battery;

    }

    public Atm(AtmLocation atmLocation, String atmName, Date installedDate, String serialNo, String status,
            String alert, Date livePktTime, int tray1, int tray2, int reject1, int reject2, String atmCode,
            Integer tray1NoteValue, Integer tray2NoteValue, Integer batLevel, Set<CashOut> cashOuts,
            Set<Alerts> alertses, Set<AtmReload> atmReloads, Set<AssignedAtm> assignedAtms, Set<Notes> noteses) {
        this.atmLocation = atmLocation;
        this.atmName = atmName;
        this.installedDate = installedDate;
        this.serialNo = serialNo;
        this.status = status;
        this.alert = alert;
        this.livePktTime = livePktTime;
        this.tray1 = tray1;
        this.tray2 = tray2;
        this.reject1 = reject1;
        this.reject2 = reject2;
        this.tray1NoteValue = tray1NoteValue;
        this.tray2NoteValue = tray2NoteValue;
        this.atmReloads = atmReloads;
         this.batLevel = batLevel;
        this.cashOuts = cashOuts;
        this.alertses = alertses;
        this.atmReloads = atmReloads;
        this.assignedAtms = assignedAtms;
        this.noteses = noteses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "atm_id", unique = true, nullable = false)
    public Integer getAtmId() {
        return this.atmId;
    }

    public void setAtmId(Integer atmId) {
        this.atmId = atmId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "location_id")
    public AtmLocation getAtmLocation() {
        return this.atmLocation;
    }

    public void setAtmLocation(AtmLocation atmLocation) {
        this.atmLocation = atmLocation;
    }

    @Column(name = "atm_name", length = 45)
    public String getAtmName() {
        return this.atmName;
    }

    public void setAtmName(String atmName) {
        this.atmName = atmName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "installed_date", length = 19)
    public Date getInstalledDate() {
        return this.installedDate;
    }

    public void setInstalledDate(Date installedDate) {
        this.installedDate = installedDate;
    }

    @Column(name = "serial_no", length = 20)
    public String getSerialNo() {
        return this.serialNo;
    }

    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo;
    }

    @Column(name = "status", length = 45)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Column(name = "alert", length = 1)
    public String getAlert() {
        return this.alert;
    }

    public void setAlert(String alert) {
        this.alert = alert;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "live_pkt_time", nullable = false, length = 19)
    public Date getLivePktTime() {
        return this.livePktTime;
    }

    public void setLivePktTime(Date livePktTime) {
        this.livePktTime = livePktTime;
    }

    @Column(name = "tray1", nullable = false)
    public int getTray1() {
        return this.tray1;
    }

    public void setTray1(int tray1) {
        this.tray1 = tray1;
    }

    @Column(name = "tray2", nullable = false)
    public int getTray2() {
        return this.tray2;
    }

    public void setTray2(int tray2) {
        this.tray2 = tray2;
    }

    @Column(name = "reject1", nullable = false)
    public int getReject1() {
        return this.reject1;
    }

    public void setReject1(int reject1) {
        this.reject1 = reject1;
    }

    @Column(name = "reject2", nullable = false)
    public int getReject2() {
        return this.reject2;
    }

    public void setReject2(int reject2) {
        this.reject2 = reject2;
    }

    @Column(name= "batteryLevel")
    public Integer getbatLevel() {
        return this.batLevel;
    }
    
    public void setbatLevel(Integer batLevel) {
        this.batLevel = batLevel;
    }

    @Column(name = "atm_code", nullable = false, length = 9)
    public String getAtmCode() {
        return this.atmCode;
    }

    public void setAtmCode(String atmCode) {
        this.atmCode = atmCode;
    }

    @Column(name = "tray1_note_value")
    public Integer getTray1NoteValue() {
        return this.tray1NoteValue;
    }

    public void setTray1NoteValue(Integer tray1NoteValue) {
        this.tray1NoteValue = tray1NoteValue;
    }

    @Column(name = "tray2_note_value")
    public Integer getTray2NoteValue() {
        return this.tray2NoteValue;
    }

    public void setTray2NoteValue(Integer tray2NoteValue) {
        this.tray2NoteValue = tray2NoteValue;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "atm")
    public Set<CashOut> getCashOuts() {
        return this.cashOuts;
    }

    public void setCashOuts(Set<CashOut> cashOuts) {
        this.cashOuts = cashOuts;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "atm")
    public Set<Alerts> getAlertses() {
        return this.alertses;
    }

    public void setAlertses(Set<Alerts> alertses) {
        this.alertses = alertses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "atm")
    public Set<AtmReload> getAtmReloads() {
        return this.atmReloads;
    }

    public void setAtmReloads(Set<AtmReload> atmReloads) {
        this.atmReloads = atmReloads;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "atm")
    public Set<AssignedAtm> getAssignedAtms() {
        return this.assignedAtms;
    }

    public void setAssignedAtms(Set<AssignedAtm> assignedAtms) {
        this.assignedAtms = assignedAtms;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "atm")
    public Set<Notes> getNoteses() {
        return this.noteses;
    }

    public void setNoteses(Set<Notes> noteses) {
        this.noteses = noteses;
    }

}
