package lk.dialoglab.ezcash.domain;

// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AtmLocation generated by hbm2java
 */
@Entity
@Table(name = "atm_location", catalog = "cashatm")
public class AtmLocation implements java.io.Serializable {

    private Integer locationId;
    private String locationName;
    private String locationX;
    private String locationY;
    private Set<Atm> atms = new HashSet<Atm>(0);

    public AtmLocation() {
    }

    public AtmLocation(String locationName, String locationX, String locationY) {
        this.locationName = locationName;
        this.locationX = locationX;
        this.locationY = locationY;
    }

    public AtmLocation(String locationName, String locationX, String locationY, Set<Atm> atms) {
        this.locationName = locationName;
        this.locationX = locationX;
        this.locationY = locationY;
        this.atms = atms;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "location_id", unique = true, nullable = false)
    public Integer getLocationId() {
        return this.locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    @Column(name = "location_name", nullable = false, length = 45)
    public String getLocationName() {
        return this.locationName;
    }

    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    @Column(name = "locationX", nullable = false, length = 45)
    public String getLocationX() {
        return this.locationX;
    }

    public void setLocationX(String locationX) {
        this.locationX = locationX;
    }

    @Column(name = "locationY", nullable = false, length = 45)
    public String getLocationY() {
        return this.locationY;
    }

    public void setLocationY(String locationY) {
        this.locationY = locationY;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "atmLocation")
    public Set<Atm> getAtms() {
        return this.atms;
    }

    public void setAtms(Set<Atm> atms) {
        this.atms = atms;
    }

}
