package lk.dialoglab.ezcash.domain;

// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * CashOut generated by hbm2java
 */
@Entity
@Table(name = "cash_out", catalog = "cashatm")
public class CashOut implements java.io.Serializable {

    private Integer cashOutId;
    private Atm atm;
    private Date cashOutDate;
    private String phoneNumber;
    private Double amount;
    private Integer status;
    private String responseId;
    private Set<Transactions> transactionses = new HashSet<Transactions>(0);

    public CashOut() {
    }

    public CashOut(Atm atm, Date cashOutDate, String phoneNumber, Double amount, Integer status, String responseId,
            Set<Transactions> transactionses) {
        this.atm = atm;
        this.cashOutDate = cashOutDate;
        this.phoneNumber = phoneNumber;
        this.amount = amount;
        this.status = status;
        this.responseId = responseId;
        this.transactionses = transactionses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "cash_out_id", unique = true, nullable = false)
    public Integer getCashOutId() {
        return this.cashOutId;
    }

    public void setCashOutId(Integer cashOutId) {
        this.cashOutId = cashOutId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @Fetch(FetchMode.JOIN)
    @JoinColumn(name = "atm_id")
    public Atm getAtm() {
        return this.atm;
    }

    public void setAtm(Atm atm) {
        this.atm = atm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "cash_out_date", length = 19)
    public Date getCashOutDate() {
        return this.cashOutDate;
    }

    public void setCashOutDate(Date cashOutDate) {
        this.cashOutDate = cashOutDate;
    }

    @Column(name = "phone_number", length = 45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "amount", precision = 7, scale = 4)
    public Double getAmount() {
        return this.amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    @Column(name = "status")
    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    @Column(name = "response_id", length = 45)
    public String getResponseId() {
        return this.responseId;
    }

    public void setResponseId(String responseId) {
        this.responseId = responseId;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cashOut")
    public Set<Transactions> getTransactionses() {
        return this.transactionses;
    }

    public void setTransactionses(Set<Transactions> transactionses) {
        this.transactionses = transactionses;
    }

}
