package lk.dialoglab.ezcash.domain;

// Generated May 11, 2015 9:40:20 AM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Didmap generated by hbm2java
 */
@Entity
@Table(name = "didmap", catalog = "cashatm")
public class Didmap implements java.io.Serializable {

    private Integer mapno;
    private String did;
    private String phone;
    private String name;

    public Didmap() {
    }

    public Didmap(String did, String phone, String name) {
        this.did = did;
        this.phone = phone;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "mapno", unique = true, nullable = false)
    public Integer getMapno() {
        return this.mapno;
    }

    public void setMapno(Integer mapno) {
        this.mapno = mapno;
    }

    @Column(name = "did", nullable = false, length = 15)
    public String getDid() {
        return this.did;
    }

    public void setDid(String did) {
        this.did = did;
    }

    @Column(name = "phone", nullable = false, length = 15)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "name", nullable = false, length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
