package lk.dialoglab.ezcash.domain;

// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes", catalog = "cashatm")
public class Notes implements java.io.Serializable {

    private int noteId;
    private Atm atm;
    private String title;
    private String comments;

    public Notes() {
    }

    public Notes(int noteId, Atm atm, String title, String comments) {
        this.noteId = noteId;
        this.atm = atm;
        this.title = title;
        this.comments = comments;
    }

    @Id
    @Column(name = "note_id", unique = true, nullable = false)
    public int getNoteId() {
        return this.noteId;
    }

    public void setNoteId(int noteId) {
        this.noteId = noteId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "atm_id", nullable = false)
    public Atm getAtm() {
        return this.atm;
    }

    public void setAtm(Atm atm) {
        this.atm = atm;
    }

    @Column(name = "title", nullable = false, length = 45)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "comments", nullable = false, length = 45)
    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

}
