package lk.dialoglab.ezcash.domain;

// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Operator generated by hbm2java
 */
@Entity
@Table(name = "operator", catalog = "cashatm")
public class Operator implements java.io.Serializable {

    private Integer operatorId;
    private String operatorName;
    private int phoneNumber;
    private String email;
    private int operatorPin;
    private int operatorType;
    private Set<AtmReload> atmReloads = new HashSet<AtmReload>(0);
    private Set<AssignedAtm> assignedAtms = new HashSet<AssignedAtm>(0);

    public Operator() {
    }

    public Operator(String operatorName, int phoneNumber, String email, int operatorPin, int operatorType) {
        this.operatorName = operatorName;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.operatorPin = operatorPin;
        this.operatorType = operatorType;
    }

    public Operator(String operatorName, int phoneNumber, String email, int operatorPin, int operatorType,
            Set<AtmReload> atmReloads, Set<AssignedAtm> assignedAtms) {
        this.operatorName = operatorName;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.operatorPin = operatorPin;
        this.operatorType = operatorType;
        this.atmReloads = atmReloads;
        this.assignedAtms = assignedAtms;

    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "operator_id", unique = true, nullable = false)
    public Integer getOperatorId() {
        return this.operatorId;
    }

    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    @Column(name = "operator_name", nullable = false, length = 25)
    public String getOperatorName() {
        return this.operatorName;
    }

    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    @Column(name = "phone_number", nullable = false)
    public int getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(int phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    @Column(name = "email", nullable = false, length = 45)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "operator_pin", nullable = false)
    public int getOperatorPin() {
        return this.operatorPin;
    }

    public void setOperatorPin(int operatorPin) {
        this.operatorPin = operatorPin;
    }

    @Column(name = "operator_type", nullable = false)
    public int getOperatorType() {
        return this.operatorType;
    }

    public void setOperatorType(int operatorType) {
        this.operatorType = operatorType;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "operator")
    public Set<AtmReload> getAtmReloads() {
        return this.atmReloads;
    }

    public void setAtmReloads(Set<AtmReload> atmReloads) {
        this.atmReloads = atmReloads;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "operator")
    @Fetch(FetchMode.JOIN)
    public Set<AssignedAtm> getAssignedAtms() {
        return this.assignedAtms;
    }

    public void setAssignedAtms(Set<AssignedAtm> assignedAtms) {
        this.assignedAtms = assignedAtms;
    }

}
