package lk.dialoglab.ezcash.domain;
// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Transactions generated by hbm2java
 */
@Entity
@Table(name="transactions"
    ,catalog="cashatm"
)
public class Transactions  implements java.io.Serializable {


     private Integer transactionId;
     private AtmReload atmReload;
     private CashOut cashOut;
     private double amount;
     private Integer tray1;
     private Integer tray2;
     private Integer reject1;
     private Integer reject2;

    public Transactions() {
    }

	
    public Transactions(double amount) {
        this.amount = amount;
    }
    public Transactions(AtmReload atmReload, CashOut cashOut, double amount, Integer tray1, Integer tray2, Integer reject1, Integer reject2) {
       this.atmReload = atmReload;
       this.cashOut = cashOut;
       this.amount = amount;
       this.tray1 = tray1;
       this.tray2 = tray2;
       this.reject1 = reject1;
       this.reject2 = reject2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="transaction_id", unique=true, nullable=false)
    public Integer getTransactionId() {
        return this.transactionId;
    }
    
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

@ManyToOne
    @JoinColumn(name="reload_id")
    public AtmReload getAtmReload() {
        return this.atmReload;
    }
    
    public void setAtmReload(AtmReload atmReload) {
        this.atmReload = atmReload;
    }

@ManyToOne(fetch=FetchType.LAZY)
@Fetch(FetchMode.JOIN)
    @JoinColumn(name="cash_out_id")
    public CashOut getCashOut() {
        return this.cashOut;
    }
    
    public void setCashOut(CashOut cashOut) {
        this.cashOut = cashOut;
    }

    
    @Column(name="amount", nullable=true, precision=22, scale=0)
    public double getAmount() {
        return this.amount;
    }
    
    public void setAmount(double amount) {
        this.amount = amount;
    }

    
    @Column(name="tray1")
    public Integer getTray1() {
        return this.tray1;
    }
    
    public void setTray1(Integer tray1) {
        this.tray1 = tray1;
    }

    
    @Column(name="tray2")
    public Integer getTray2() {
        return this.tray2;
    }
    
    public void setTray2(Integer tray2) {
        this.tray2 = tray2;
    }

    
    @Column(name="reject1")
    public Integer getReject1() {
        return this.reject1;
    }
    
    public void setReject1(Integer reject1) {
        this.reject1 = reject1;
    }

    
    @Column(name="reject2")
    public Integer getReject2() {
        return this.reject2;
    }
    
    public void setReject2(Integer reject2) {
        this.reject2 = reject2;
    }




}


