package lk.dialoglab.ezcash.domain;

// Generated Mar 30, 2015 2:46:26 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserType generated by hbm2java
 */
@Entity
@Table(name = "user_type", catalog = "cashatm")
public class UserType implements java.io.Serializable {

    private Integer typeId;
    private String typeName;
    private Set<WebUser> webUsers = new HashSet<WebUser>(0);

    public UserType() {
    }

    public UserType(String typeName) {
        this.typeName = typeName;
    }

    public UserType(String typeName, Set<WebUser> webUsers) {
        this.typeName = typeName;
        this.webUsers = webUsers;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "type_id", unique = true, nullable = false)
    public Integer getTypeId() {
        return this.typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    @Column(name = "type_name", nullable = false, length = 45)
    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "userType")
    public Set<WebUser> getWebUsers() {
        return this.webUsers;
    }

    public void setWebUsers(Set<WebUser> webUsers) {
        this.webUsers = webUsers;
    }

}
